// export const LOGIN = "APP/LOGIN"
// export const REGISTER = "APP/REGISTER"
// export const LOGOUT = "APP/LOGOUT"

// export const SHOW_ALERT = "APP/SHOW_ALERT"
// export const HIDE_ALERT = "APP/HIDE_ALERT"

export const SET_RECORD_BEING_UPDATED = "APP/SET_RECORD_BEING_UPDATED"           
export const UNSET_RECORD_BEING_UPDATED = "APP/UNSET_RECORD_BEING_UPDATED"

    
export const DELETE_RECORD = "PASSWORD/DELETE_RECORD"

export const UPDATE_RECORD = "PASSWORD/UPDATE_RECORD"

export const SET_RECORD_BEING_CREATED = "APP/SET_RECORD_BEING_CREATED"           
export const UNSET_RECORD_BEING_CREATED = "APP/UNSET_RECORD_BEING_CREATED"   

export const CREATE_RECORD = "PASSWORD/CREATE_RECORD"

