//in order of implementation ^_^

export const SET_RECORD_BEING_UPDATED = "APP/SET_RECORD_BEING_UPDATED"           
export const UNSET_RECORD_BEING_UPDATED = "APP/UNSET_RECORD_BEING_UPDATED"
    
export const DELETE_RECORD = "PASSWORD/DELETE_RECORD"

export const UPDATE_RECORD = "PASSWORD/UPDATE_RECORD"

export const SET_RECORD_BEING_CREATED = "APP/SET_RECORD_BEING_CREATED"           
export const UNSET_RECORD_BEING_CREATED = "APP/UNSET_RECORD_BEING_CREATED"   

export const CREATE_RECORD = "PASSWORD/CREATE_RECORD"

// export const LOGIN = "APP/LOGIN"
// export const REGISTER = "APP/REGISTER"
// export const LOGOUT = "APP/LOGOUT"
